#!/usr/bin/env node
// scripts/check-readme.mjs
//
// Doc-drift guard: render the autogen Commands block from `dist/freelo.js --introspect`
// and compare it against the committed README. With --write, rewrite the README in place.
//
// Exit codes:
//   0 — match (CI mode) or write succeeded
//   1 — drift detected (CI mode only)
//   2 — environmental error (missing dist, missing markers, malformed envelope, etc.)
//
// Spec: docs/specs/0006-readme-autocheck.md

import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const BEGIN_MARKER = '<!-- BEGIN AUTOGEN COMMANDS -->';
const END_MARKER = '<!-- END AUTOGEN COMMANDS -->';
const HEADER_COMMENT =
  '<!-- Generated by scripts/check-readme.mjs from `freelo --introspect`. Do not edit by hand. -->';

const args = process.argv.slice(2);
const writeMode = args.includes('--write');

// Resolve repo root: env var > script-relative default (../).
const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(process.env.FREELO_README_REPO_ROOT ?? join(here, '..'));

const distPath = join(repoRoot, 'dist', 'freelo.js');
const readmePath = join(repoRoot, 'README.md');

function fail(code, message) {
  process.stderr.write(`check-readme: ${message}\n`);
  process.exit(code);
}

if (!existsSync(distPath)) {
  fail(2, `dist/freelo.js not found at ${distPath} — run \`pnpm build\` first`);
}

if (!existsSync(readmePath)) {
  fail(2, `README.md not found at ${readmePath}`);
}

// Run --introspect.
const result = spawnSync(process.execPath, [distPath, '--introspect'], {
  encoding: 'utf8',
  windowsHide: true,
});

if (result.error) {
  fail(2, `failed to spawn ${distPath}: ${result.error.message}`);
}
if (result.status !== 0) {
  const stderr = (result.stderr ?? '').trim();
  fail(2, `\`node dist/freelo.js --introspect\` exited with code ${result.status}${stderr ? `\n${stderr}` : ''}`);
}

let envelope;
try {
  envelope = JSON.parse(result.stdout);
} catch (err) {
  fail(2, `failed to parse --introspect JSON: ${err.message}`);
}

if (envelope?.schema !== 'freelo.introspect/v1') {
  fail(2, `unexpected envelope schema: got ${JSON.stringify(envelope?.schema)}, expected "freelo.introspect/v1"`);
}
if (!Array.isArray(envelope?.data?.commands)) {
  fail(2, 'envelope.data.commands is not an array');
}

const rendered = renderBlock(envelope.data.commands);

const readmeRaw = readFileSync(readmePath, 'utf8');
// Normalize CRLF to LF for comparison; --write always emits LF.
const readme = readmeRaw.replace(/\r\n/g, '\n');

const beginIdx = readme.indexOf(BEGIN_MARKER);
const endIdx = readme.indexOf(END_MARKER);

if (beginIdx === -1) fail(2, `marker not found in README.md: ${BEGIN_MARKER}`);
if (endIdx === -1) fail(2, `marker not found in README.md: ${END_MARKER}`);
if (endIdx < beginIdx) fail(2, `${END_MARKER} appears before ${BEGIN_MARKER}`);

// Replace contents between markers (exclusive). The replacement is everything
// from after BEGIN_MARKER up to (but not including) END_MARKER.
const before = readme.slice(0, beginIdx + BEGIN_MARKER.length);
const after = readme.slice(endIdx);
const newReadme = `${before}\n${rendered}\n${after}`;

if (writeMode) {
  writeFileSync(readmePath, newReadme, 'utf8');
  process.stdout.write('README autogen block rewritten.\n');
  process.exit(0);
}

if (newReadme === readme) {
  process.stdout.write('README autogen block is up to date.\n');
  process.exit(0);
}

// Drift: print a unified diff to stderr.
const expectedBlock = newReadme.slice(beginIdx + BEGIN_MARKER.length + 1, newReadme.indexOf(END_MARKER) - 1);
const actualBlock = readme.slice(beginIdx + BEGIN_MARKER.length + 1, endIdx - 1);
process.stderr.write('check-readme: README autogen block is out of date.\n');
process.stderr.write('Run `pnpm fix:readme` to regenerate.\n\n');
process.stderr.write(unifiedDiff(actualBlock, expectedBlock));
process.exit(1);

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

function renderBlock(commands) {
  // Defensive: re-sort by name. Group by first space-separated segment.
  const sorted = [...commands].sort((a, b) => a.name.localeCompare(b.name));
  const groups = new Map();
  for (const cmd of sorted) {
    const group = cmd.name.split(' ', 1)[0];
    if (!groups.has(group)) groups.set(group, []);
    groups.get(group).push(cmd);
  }
  const groupNames = [...groups.keys()].sort();

  const lines = [];
  lines.push(HEADER_COMMENT);
  lines.push('');

  for (let i = 0; i < groupNames.length; i++) {
    const group = groupNames[i];
    lines.push(`### ${group}`);
    lines.push('');
    for (const cmd of groups.get(group)) {
      lines.push(renderCommandLine(cmd));
    }
    if (i < groupNames.length - 1) lines.push('');
  }

  return lines.join('\n');
}

function renderCommandLine(cmd) {
  const argTokens = (cmd.args ?? []).map(renderArgToken);
  const head = argTokens.length > 0
    ? `\`freelo ${cmd.name} ${argTokens.join(' ')}\``
    : `\`freelo ${cmd.name}\``;
  const desc = (cmd.description ?? '').trim();
  return desc ? `- ${head} — ${desc}` : `- ${head}`;
}

function renderArgToken(arg) {
  const name = arg.variadic ? `${arg.name}...` : arg.name;
  return arg.required ? `<${name}>` : `[${name}]`;
}

// ---------------------------------------------------------------------------
// Minimal unified diff (line-by-line, no extra deps)
// ---------------------------------------------------------------------------

function unifiedDiff(actual, expected) {
  const a = actual.split('\n');
  const b = expected.split('\n');
  const out = ['--- README.md (committed)', '+++ README.md (expected)'];
  // Naive: emit the longest run, marking adds and removes.
  // Good enough for human reading in CI logs; this is a drift signal, not a patch tool.
  const max = Math.max(a.length, b.length);
  for (let i = 0; i < max; i++) {
    const left = i < a.length ? a[i] : null;
    const right = i < b.length ? b[i] : null;
    if (left === right) {
      out.push(`  ${left ?? ''}`);
    } else {
      if (left !== null) out.push(`- ${left}`);
      if (right !== null) out.push(`+ ${right}`);
    }
  }
  return out.join('\n') + '\n';
}
