import { spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..', '..');
const scriptPath = resolve(repoRoot, 'scripts', 'check-readme.mjs');

interface FakeArg {
  name: string;
  required: boolean;
  variadic: boolean;
  description: string;
}

interface FakeFlag {
  name: string;
  short: string | null;
  type: 'boolean' | 'string';
  required: boolean;
  description: string;
  repeatable: boolean;
}

interface FakeCommand {
  name: string;
  description: string;
  args: FakeArg[];
  flags: FakeFlag[];
  output_schema: string;
  destructive: boolean;
}

interface FakeEnvelope {
  schema: string;
  data: { version: string; commands: FakeCommand[] };
}

const SAMPLE_ENVELOPE: FakeEnvelope = {
  schema: 'freelo.introspect/v1',
  data: {
    version: '0.0.0-test',
    commands: [
      {
        name: 'auth login',
        description: 'Log in to Freelo.',
        args: [],
        flags: [],
        output_schema: 'freelo.auth.login/v1',
        destructive: false,
      },
      {
        name: 'auth logout',
        description: 'Log out.',
        args: [],
        flags: [],
        output_schema: 'freelo.auth.logout/v1',
        destructive: false,
      },
      {
        name: 'config get',
        description: 'Get a config key.',
        args: [
          {
            name: 'key',
            required: true,
            variadic: false,
            description: '',
          },
        ],
        flags: [],
        output_schema: 'freelo.config.get/v1',
        destructive: false,
      },
      {
        name: 'config set',
        description: 'Set a config key.',
        args: [
          { name: 'key', required: true, variadic: false, description: '' },
          { name: 'value', required: true, variadic: false, description: '' },
        ],
        flags: [],
        output_schema: 'freelo.config.set/v1',
        destructive: false,
      },
    ],
  },
};

let scratch: string;

function makeFakeDist(envelope: FakeEnvelope): void {
  const distDir = join(scratch, 'dist');
  mkdirSync(distDir, { recursive: true });
  const json = JSON.stringify(envelope);
  // Use process.stdout.write so the JSON is emitted exactly once with no
  // trailing newline (mirrors the real binary's behavior).
  const stub = `process.stdout.write(${JSON.stringify(json)});\n`;
  writeFileSync(join(distDir, 'freelo.js'), stub, 'utf8');
}

function renderExpected(envelope: FakeEnvelope): string {
  // Mirror the script's renderer for use in assertions.
  const sorted = [...envelope.data.commands].sort((a, b) => a.name.localeCompare(b.name));
  const groups = new Map<string, FakeCommand[]>();
  for (const cmd of sorted) {
    const g = cmd.name.split(' ', 1)[0]!;
    if (!groups.has(g)) groups.set(g, []);
    groups.get(g)!.push(cmd);
  }
  const groupNames = [...groups.keys()].sort();
  const lines: string[] = [];
  lines.push(
    '<!-- Generated by scripts/check-readme.mjs from `freelo --introspect`. Do not edit by hand. -->',
  );
  lines.push('');
  for (let i = 0; i < groupNames.length; i++) {
    const g = groupNames[i]!;
    lines.push(`### ${g}`);
    lines.push('');
    for (const cmd of groups.get(g)!) {
      const tokens = cmd.args.map((a) => {
        const n = a.variadic ? `${a.name}...` : a.name;
        return a.required ? `<${n}>` : `[${n}]`;
      });
      const head =
        tokens.length > 0 ? `\`freelo ${cmd.name} ${tokens.join(' ')}\`` : `\`freelo ${cmd.name}\``;
      const desc = cmd.description.trim();
      lines.push(desc ? `- ${head} — ${desc}` : `- ${head}`);
    }
    if (i < groupNames.length - 1) lines.push('');
  }
  return lines.join('\n');
}

function writeReadme(blockBody: string): void {
  const content = `# fake\n\nIntro.\n\n<!-- BEGIN AUTOGEN COMMANDS -->\n${blockBody}\n<!-- END AUTOGEN COMMANDS -->\n\nOutro.\n`;
  writeFileSync(join(scratch, 'README.md'), content, 'utf8');
}

function runScript(args: string[] = []): { status: number | null; stdout: string; stderr: string } {
  const result = spawnSync(process.execPath, [scriptPath, ...args], {
    encoding: 'utf8',
    env: { ...process.env, FREELO_README_REPO_ROOT: scratch },
    windowsHide: true,
  });
  return {
    status: result.status,
    stdout: result.stdout ?? '',
    stderr: result.stderr ?? '',
  };
}

beforeEach(() => {
  scratch = mkdtempSync(join(tmpdir(), 'freelo-readme-check-'));
});

afterEach(() => {
  rmSync(scratch, { recursive: true, force: true });
});

describe('scripts/check-readme.mjs', () => {
  it('exits 0 when the autogen block matches the live introspect output', () => {
    makeFakeDist(SAMPLE_ENVELOPE);
    writeReadme(renderExpected(SAMPLE_ENVELOPE));
    const { status, stdout } = runScript();
    expect(status).toBe(0);
    expect(stdout).toContain('up to date');
  });

  it('exits 1 with a diff on stderr when the block is stale', () => {
    makeFakeDist(SAMPLE_ENVELOPE);
    writeReadme('stale content here');
    const { status, stderr } = runScript();
    expect(status).toBe(1);
    expect(stderr).toContain('out of date');
    expect(stderr).toContain('pnpm fix:readme');
    expect(stderr).toContain('+ ### auth');
  });

  it('rewrites the README and exits 0 with --write', () => {
    makeFakeDist(SAMPLE_ENVELOPE);
    writeReadme('stale content here');
    const { status, stdout } = runScript(['--write']);
    expect(status).toBe(0);
    expect(stdout).toContain('rewritten');
    const updated = readFileSync(join(scratch, 'README.md'), 'utf8');
    expect(updated).toContain(renderExpected(SAMPLE_ENVELOPE));
    // Re-running in CI mode should now report up-to-date.
    const after = runScript();
    expect(after.status).toBe(0);
  });

  it('exits 2 with a clear message when markers are missing', () => {
    makeFakeDist(SAMPLE_ENVELOPE);
    writeFileSync(join(scratch, 'README.md'), '# fake\n\nNo markers here.\n', 'utf8');
    const { status, stderr } = runScript();
    expect(status).toBe(2);
    expect(stderr).toContain('BEGIN AUTOGEN COMMANDS');
  });

  it('exits 2 when dist/freelo.js is missing', () => {
    // No makeFakeDist call.
    writeReadme('placeholder');
    const { status, stderr } = runScript();
    expect(status).toBe(2);
    expect(stderr).toContain('dist/freelo.js not found');
  });

  it('groups auth and config under separate alphabetic headings', () => {
    makeFakeDist(SAMPLE_ENVELOPE);
    writeReadme('placeholder'); // mismatch — will rewrite
    runScript(['--write']);
    const updated = readFileSync(join(scratch, 'README.md'), 'utf8');
    const authIdx = updated.indexOf('### auth');
    const configIdx = updated.indexOf('### config');
    expect(authIdx).toBeGreaterThan(0);
    expect(configIdx).toBeGreaterThan(authIdx);
    expect(updated).toContain('- `freelo auth login` — Log in to Freelo.');
    expect(updated).toContain('- `freelo config get <key>` — Get a config key.');
    expect(updated).toContain('- `freelo config set <key> <value>` — Set a config key.');
  });

  it('renders optional and variadic arg tokens correctly', () => {
    const envelope: FakeEnvelope = {
      schema: 'freelo.introspect/v1',
      data: {
        version: '0.0.0-test',
        commands: [
          {
            name: 'foo bar',
            description: 'Tokens.',
            args: [
              { name: 'req', required: true, variadic: false, description: '' },
              { name: 'opt', required: false, variadic: false, description: '' },
              { name: 'rest', required: false, variadic: true, description: '' },
            ],
            flags: [],
            output_schema: 'freelo.foo.bar/v1',
            destructive: false,
          },
          {
            name: 'foo nodesc',
            description: '',
            args: [],
            flags: [],
            output_schema: 'freelo.foo.nodesc/v1',
            destructive: false,
          },
        ],
      },
    };
    makeFakeDist(envelope);
    writeReadme('placeholder');
    runScript(['--write']);
    const updated = readFileSync(join(scratch, 'README.md'), 'utf8');
    expect(updated).toContain('- `freelo foo bar <req> [opt] [rest...]` — Tokens.');
    // No description → no em-dash.
    expect(updated).toMatch(/- `freelo foo nodesc`\n/);
  });
});
